Created article service
Nekitosn/MyBlog pull request #12
Opened 2023-02-19 22:32 UTC by Nekitosn

feat - Changed entity article;
feat - Added migration where changed entity article;
feat - Created article service;
feat - Created auto mapper for article;
feat - Created dto jwt info.

2023-02-20 07:26 UTC, Vladislawv requested changes

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Infrastructure/Entities/Article.cs
> +
rename

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Infrastructure/Entities/Enum/Topic.cs
> +    Sport = 4,
incorrect word

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/IArticleService.cs
> +    public Task<ArticleDto> CreateAsync(JWTInfo userJwtInfo, ArticleDtoInput articleInput);
придерживайся одного: у тебя в entity - topic, а здесь - theme

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +            .ToListAsync();
lamba vars naming

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
you already throw this exception in the user sercice. Here it is unnecessary

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +            .ToListAsync();
lambda vars

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +            .ToListAsync();
lamba vars

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
lambda

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
if it is bool return type, how should you call this method ?

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
also, rename userJwtInfo var

2023-02-20 07:26 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        return await _context.Articles.AnyAsync(a => a.Title == articleInput.Title && a.Id != article.Id);
think about method naming

2023-02-20 20:21 UTC, Nekitosn commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
userJwtInfo какое плохое зло тебе сделало?

2023-02-20 21:58 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
а ты подумай

2023-02-20 21:58 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
включи телепатические способности

2023-02-20 22:01 UTC, Nekitosn commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
Ну блин, это переменная, где храниться jwttoken юзера
Как её назвать под другому? Если просто jwtinfo, то может быть не понятно что именно это, а так все четко и ясно

2023-02-20 22:04 UTC, Vladislawv requested changes

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Infrastructure/Entities/Article.cs
рассинхрон

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
also, you forgot to rename method

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
>          {
unnecessary whitspaces in the if cases

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        var articleById = await GetArticleByIdAsync(id);
rename this method - you return bool type
the name of your method should give me the answer what is going on

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
>      {
what is return type ?

2023-02-20 22:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        var articleById = await GetArticleByIdAsync(id);
also, think about articleById variable renaming

2023-02-20 22:05 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
userToken не лучше звучит ?

2023-02-20 22:08 UTC, Nekitosn commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +    }
Мен, ты как всегда прав

2023-02-22 23:39 UTC, Vladislawv requested changes

2023-02-22 23:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
>              .Where(article => article.UserId == userId)
не переноси, если влезает в 1 строку

2023-02-22 23:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
why did you call this method ?

2023-02-22 23:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
it is better, to init this property in the entity

2023-02-22 23:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        {
do not split if and foreach cases (if it is too long, save it on the local variable and use this one in the if case)

2023-02-22 23:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        };
you can`t seems better, right ?

2023-02-23 20:45 UTC, Vladislawv requested changes

2023-02-23 20:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
it is very small logic, so check the list in this one method

2023-02-23 20:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
also, you can check the list for null by continue your linq chain:
.ToListAsync() ?? throw new Exception();

2023-02-23 20:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +
просто article, ведь он может быть и не exist

2023-02-23 20:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
> +        if (isExistTitle)
вот так не делай, лучше отступай если у тебя 2 и больше строк занимает
так же, не забывай что в английском тоже прямой порядок слов
сначала подлежащее, потом сказуемое
isTitleExist
пересмотри везде

2023-02-23 20:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/AutoMapper/ArticleMappingProfile.cs
> +    }
это разве не излишне ? 
у тебя в сущности уже стоит инициализация

2023-02-24 07:52 UTC, Vladislawv approved these changes

2023-02-24 11:13 UTC, merged