Implemented mailing in auth controller
Nekitosn/MyBlog pull request #18
Opened 2023-03-05 22:15 UTC by Nekitosn

feat - Implemented mailing in auth controller*;
feat - Created email service;
fix - Fixed names in claim parser.

2023-03-06 19:20 UTC, Vladislawv requested changes

2023-03-06 19:20 UTC, Vladislawv commented on MyBlog.API/Controllers/AuthController.cs
> +    public AuthController(IAuthService authService, IEmailService emailService)
отступ

2023-03-06 19:20 UTC, Vladislawv commented on MyBlog.API/Controllers/AuthController.cs
>      }
mailingService не лучше ?

2023-03-06 19:20 UTC, Vladislawv commented on MyBlog.API/Controllers/AuthController.cs
> +
successfull

2023-03-06 19:20 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/EmailService.cs
> +        mimeMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html)
сделай отправку сообщений анонимной, что бы получатели не видели, кому ещё приходили письма

2023-03-06 19:20 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/EmailService.cs
> +}
так же, можно реализовать метод рассылки от одного ко многим (админ - юзеры)

2023-03-08 21:46 UTC, Vladislawv requested changes

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/AuthController.cs
> +    public async Task<IActionResult> RegisterAsync([FromForm] UserDtoInput userInput, [FromForm] bool isSubscribeToEmail)
бульку можно FromQuery

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/AuthController.cs
> +        await _mailingService.SendEmailToUserAsync("You successfully register on site 'My Blog'.", userInput.Email);
registered

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +[ApiController]
nice root, man

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +    }
?

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +    public async Task<IActionResult> SendEmailToUserAsync([FromForm] string message, [FromForm] string recipientEmail)
логичнее в начале указать получаетеля, а потом сообщение
посмотри везде

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +    }
лучше разбей на 2 ендпоинта

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.API/appsettings.json
> +    "UseSSL": true
лучше всё в сикреты

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.Infrastructure/Entities/User.cs
>  }
я бы, всё же, заменил на бульку

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
> +    }
лучше поменять местами методы

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
> +            Select(user => user.Email).
можно ли убрать == true ?

2023-03-08 21:46 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
> +    }
метод по сути должен вызываться в кейсе при подписке/отписке от рассылки => можно не выносить в отдельный метод

2023-03-11 11:55 UTC, Nekitosn commented on MyBlog.API/Controllers/MailingController.cs
> +[ApiController]
ахахах, оце я прошляпился

2023-03-12 08:36 UTC, Vladislawv requested changes

2023-03-12 08:36 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +        await _mailingService.UnsubscribeOnMailingAsync(_currentUserJwtInfo.Result.Id);
как называется твой контроллер ?

2023-03-12 08:36 UTC, Vladislawv commented on MyBlog.API/Controllers/MailingController.cs
> +    [Authorize]
не-вни-ма-тель-ный

2023-03-12 08:36 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/IMailingService.cs
> +    public Task UnsubscribeOnMailingAsync(int id);
не стоит дублировать название сервиса
SubscribeTo
UnsubscribeFrom

2023-03-12 08:36 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
>              Select(user => user.Email).
IsSubscribed на первое место в linq

2023-03-12 08:36 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
>              Where(user => user.Role == Role.User).
название метода думай сам)

2023-03-12 20:31 UTC, Vladislawv approved these changes

2023-03-12 20:31 UTC, Vladislawv commented on MyBlog.Services/Areas/Mailing/MailingService.cs
>      {
GetSubscribedEmailsAsync pretty, yeah ?

2023-03-12 23:54 UTC, merged