Created comment service/controller
Nekitosn/MyBlog pull request #20
Opened 2023-03-16 12:08 UTC by Nekitosn

feat - Created comment service;
feat - Created comment controller;
feat - Created validator for comment input;
feat - Created comment mapper;
feat - Created comment dto`s;
fix - Fixed controller attribute.

2023-03-16 19:39 UTC, Vladislawv requested changes

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.API/Controllers/FeedbackController.cs
> +    {
у тебя название контроллера не совпадает с возвращаемой сущностью, поэтому переименуй методы

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.API/Controllers/FeedbackController.cs
> +    {
ByArticleId

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.API/Controllers/FeedbackController.cs
> +    [ProducesResponseType(typeof(CommentDto), StatusCodes.Status200OK)]
commentId:int
пересмотри везде

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.API/Controllers/FeedbackController.cs
> +    {
int commentId

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Articles/ArticleService.cs
>          };
You do not have access/permission

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/AutoMapper/Dto/CommentInputDto.cs
> +}
сюда тоже можно prop с UserId

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/Validators/CommentInputDtoValidator.cs
> +
2 and 150 characters

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/Validators/CommentInputDtoValidator.cs
> +    }
?

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/Validators/CommentInputDtoValidator.cs
> +                ? throw new BadRequestException("You need entering the number") : true);
перепиши этот участок (можно не выбрасывать ошибку, а использовать .WithMessage)
тогда можно будет избавиться от лишнего

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +    }
зачем в этом методе выкидывать исключение ?

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +    }
то же самое

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +
ArticleIsNot

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +
почему ты так хейтишь is ?

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        };
you do not have permission/access

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        {
!await

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        {
только Админы могут редактировать комментарии ?

2023-03-16 19:39 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        }
isssssssssssssssssssssss

2023-03-17 13:33 UTC, Nekitosn commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        {
Если данная создатель этой статьи НЕ этот пользователь и у него НЕ роль админ то выкидуется ошибка, здесь может удалять и редактировать либо пользователь который написал, либо если админ, здесь правильная логика.

2023-03-17 13:35 UTC, Nekitosn commented on MyBlog.Services/Areas/Comments/AutoMapper/Dto/CommentInputDto.cs
> +}
Данная информация берется с токена

2023-03-17 13:41 UTC, Nekitosn commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        {
Отписал в телегу

2023-03-17 13:53 UTC, Nekitosn commented on MyBlog.Services/Areas/Comments/CommentService.cs
> +        }
Отписал в телегу

2023-03-18 08:28 UTC, Vladislawv approved these changes

2023-03-18 08:28 UTC, Vladislawv commented on MyBlog.API/Controllers/FeedbackController.cs
> +    public async Task<IActionResult> GetListCommentAsync()
GetCommentListAsync

2023-03-18 08:28 UTC, Vladislawv commented on MyBlog.Services/Areas/Comments/CommentService.cs
>          var comments = await _context.Comments
ByArticleId

2023-03-18 10:46 UTC, merged