Implemented fluent validation
Nekitosn/MyBlog pull request #7
Opened 2023-02-10 11:48 UTC by Nekitosn

feat - Implemented fluent validation;
feat - Update exception handling middleware and related classes; 
chore - Deleted white spaces in project, unless usings, and unless property in user dto input.

2023-02-10 23:45 UTC, Vladislawv requested changes

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +
firstName =>

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +
lastName =>

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +
password =>

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +
look in the EmailAddress method implementation. All necessary rules is there, so you can remove .MaximumLength rule

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +}
`+ => ругается на плюс ?

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Exception/CustomException.cs
> +    public object? ResponseAdditionalInfo { get; }
remove here empty line

2023-02-10 23:45 UTC, Vladislawv commented on MyBlog.Services/Exception/ValidateErrorException.cs
> +}
public class ValidationErrorException
[MyBlog.Services/Exception/ValidateErrorException.cs]

2023-02-10 23:55 UTC, Nekitosn commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +}
Нет, я сделал экранирование с помощью \. Я так и не нашел норм регекст, поэтому посмотрел что это такое и сам написал, и проверил, все работает если ввести как в примере, а если допустим больше символов, или меньше и т.д. то пишет неверный формат

2023-02-11 00:03 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +}
![image](https://user-images.githubusercontent.com/87234450/218224260-60be5337-a00d-459b-b86a-0ed071c056dd.png)
я про этот плюс

2023-02-11 00:04 UTC, Vladislawv commented on MyBlog.Services/Areas/Users/Validators/UserDtoInputValidator.cs
> +}
без него можно ?

2023-02-11 00:19 UTC, Vladislawv approved these changes

2023-02-11 11:48 UTC, merged